# Server Configuration
server.port=${SERVER_PORT:8080}

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reaction_challenge}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2400030993}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS / Region Infrastructure Environment Variables
server.region=${SERVER_REGION:local}
server.id=${SERVER_ID:local-server}
global.accelerator.enabled=${GLOBAL_ACCELERATOR_ENABLED:false}

# CORS Configuration
cors.origins=${CORS_ORIGINS:http://localhost:5173}
